services:
  database:
    image: mariadb:12-noble
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - TZ=Europe/Warsaw
      - MARIADB_DATABASE=${DB_NAME:-propertyvista}
      - MARIADB_USER=${DB_USER:-propertyvista}
      - MARIADB_PASSWORD=${DB_PASSWORD:-propertyvista}
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    healthcheck: # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh#compose-file-example
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  storage:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    volumes:
      - storage_data:/data
    ports:
      - "9000:9000"
    environment:
      - TZ=Europe/Warsaw
      - RUSTFS_CONSOLE_ENABLE=false
      - RUSTFS_ACCESS_KEY=${STORAGE_ACCESS_KEY:-storageaccesskey}
      - RUSTFS_SECRET_KEY=${STORAGE_SECRET_KEY:-storagesecretkey}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - cache_data:/data
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Warsaw
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${CACHE_PASSWORD:-propertyvista}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
  storage_data:
  cache_data: