import createClient from 'openapi-fetch'
import type { paths } from './generated/schema' // Generated by openapi-typescript

const client = createClient<paths>({ baseUrl: 'http://localhost:8080' })
export default client
