import { ref } from 'vue'
import createClient from 'openapi-fetch'
import type { paths, components } from './generated/schema' // Generated by openapi-typescript

const token = ref<string | null>(null)
export const setApiAccessToken = (newToken: string | null) => {
  token.value = newToken
}

type ErrorResponse = components['schemas']['ErrorResponse']
export const makeErrorResponseHumanReadable = (error: ErrorResponse): string => {
  let message = error.message || 'Wystąpił błąd'

  // Check if error has any details
  if (error.errors && Object.keys(error.errors).length > 0) {
    const details = Object.entries(error.errors)
      .map(([, msg]) => msg)
      .join('; ')
    message += `: ${details}`
  }

  return message
}

const client = createClient<paths>({
  baseUrl: import.meta.env.VITE_API_URL || 'http://localhost:8080',
  fetch: (input) => {
    const headers: Record<string, string> = {}
    if (token.value) {
      headers['Authorization'] = `Bearer ${token.value}`
    }
    const modifiedRequest = new Request(input, {
      headers: {
        ...Object.fromEntries(input.headers),
        ...headers,
      },
    })
    return fetch(modifiedRequest)
  },
})

export default client
